export const REG_API_LOADING = "REG_API_LOADING"
export const REG_API_SUCCESS = "REG_API_SUCCESS"
export const REG_API_FAILURE = "REG_API_FAILURE"


export const LOGIN_API_LOADING = "LOGIN_API_LOADING"
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS"
export const LOGIN_API_FAILURE = "LOGIN_API_FAILURE"


export const CLEAN_AUTH = 'CLEAN_AUTH'


export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE"


export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'

export const GET_CART_LOADING = "GET_CART_LOADING"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"

